FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o audit-worker ./cmd/audit-worker/main.go


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/audit-worker .

CMD ["./audit-worker"]